mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'

when@test:
    mercure:
        hubs:
            default:
                url: 'http://null/.well-known/mercure'
                jwt:
                    secret: 'a-fake-secret-a-fake-secret-a-fake-secret-a-fake-secret'
                    publish: ['*']
