# Enable stateless CSRF protection for forms and logins/logouts
framework:
    csrf_protection:
        check_header: true

turbo:
    broadcast: ~

when@test:
    turbo:
        broadcast:
            enabled: true
            doctrine_orm:
                enabled: false
